version: '3.8'
services:
  library-db:
    image: postgres:latest
    container_name: library-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  library-backend:
    image: ghcr.io/redjem-amir/library/backend:latest
    ports:
      - "5601:5601"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      AUTH_JWKURI: ${AUTH_JWKURI}
      AUTH_AUDIENCE: ${AUTH_AUDIENCE}
      AUTH_ISSUER: ${AUTH_ISSUER}
    depends_on:
      - library-db
    restart: always
  library-frontend:
    image: ghcr.io/redjem-amir/library/frontend:latest
    ports:
      - "5600:5600"
    environment:
      API_BACKEND: ${API_BACKEND}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    restart: always
volumes:
  postgres_data: