name: Deployment CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: redjem-amir
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Send docker-compose
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.SERVER }}
          port: ${{ secrets.PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./.docker/docker-compose.yml
          remote_path: /var/www/library
          args: '-o ConnectTimeout=30' 

      - name: Run PostgreSQL
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/library
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            docker login ghcr.io -u redjem-amir -p '${{ secrets.GITHUB_TOKEN }}'
            docker compose up -d library-db
            docker image prune -f

      - name: Build Image Docker Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/redjem-amir/library/backend:latest
      
      - name: Run Docker Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/library
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            export AUTH_JWKURI=${{ secrets.AUTH_JWKURI }}
            export AUTH_AUDIENCE=${{ secrets.AUTH_AUDIENCE }}
            export AUTH_ISSUER=${{ secrets.AUTH_ISSUER }}
            docker login ghcr.io -u redjem-amir -p '${{ secrets.GITHUB_TOKEN }}'
            docker compose down library-backend || true
            docker image prune -f
            docker compose pull library-backend
            docker compose up -d library-backend

      - name: Build Image Docker FrontEnd
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/redjem-amir/library/frontend:latest
          network: host
          build-args: |
            API_BACKEND=${{ secrets.API_BACKEND }}

      - name: Run Docker FrontEnd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/library
            export AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}
            export AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}
            export AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}
            export AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
            export AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}
            export API_BACKEND=${{ secrets.API_BACKEND }}
            docker login ghcr.io -u redjem-amir -p '${{ secrets.GITHUB_TOKEN }}'
            docker compose down library-frontend || true
            docker image prune -f
            docker compose pull library-frontend
            docker compose up -d library-frontend